services:
  api_velock:
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=api_velock
      - POSTGRES_PASSWORD=api_velock_pass
      - POSTGRES_DB=db_v1
    volumes:
      - api_velock_db:/postgres

volumes:
  api_velock_db:
